# Generated by Django 4.2 on 2023-04-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagy_name', models.CharField(max_length=30, unique=True)),
                ('discription', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=40)),
                ('property_image', models.FileField(upload_to='')),
                ('property_state', models.CharField(max_length=40)),
                ('property_district', models.CharField(max_length=40)),
                ('property_place', models.CharField(max_length=40)),
                ('property_country', models.CharField(max_length=40)),
                ('property_price', models.FloatField(max_length=40)),
                ('ploat_area', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('floar', models.IntegerField(blank=True, null=True)),
                ('property_discription', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.catagory')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
