# Generated by Django 4.2 on 2023-04-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.properties'),
            preserve_default=False,
        ),
    ]
